In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [2]:
data = pd.read_csv('gapminder.csv', low_memory=False)

In [3]:
data.head()

,country,incomeperperson,alcconsumption,armedforcesrate,breastcancerper100th,co2emissions,femaleemployrate,hivrate,internetuserate,lifeexpectancy,oilperperson,polityscore,relectricperperson,suicideper100th,employrate,urbanrate
0,Afghanistan,,.03,.5696534,26.8,75944000,25.6000003814697,,3.65412162280064,48.673,,0,,6.68438529968262,55.7000007629394,24.04
1,Albania,1914.99655094922,7.29,1.0247361,57.4,223747333.333333,42.0999984741211,,44.9899469578783,76.918,,9,636.341383366604,7.69932985305786,51.4000015258789,46.72
2,Algeria,2231.99333515006,.69,2.306817,23.5,2932108666.66667,31.7000007629394,.1,12.5000733055148,73.131,.42009452521537,2,590.509814347428,4.8487696647644,50.5,65.22
3,Andorra,21943.3398976022,10.17,,,,,,81,,,,,5.36217880249023,,88.92
4,Angola,1381.00426770244,5.57,1.4613288,23.1,248358000,69.4000015258789,2,9.99995388324075,51.093,,-2,172.999227388199,14.5546770095825,75.6999969482422,56.7

In [4]:
#converting to numeric
data['internetuserate'] = pd.to_numeric(data['internetuserate'], errors='coerce')
data['urbanrate'] = pd.to_numeric(data['urbanrate'], errors='coerce')

In [5]:
#deleting rows containing missing data on explanatory or response variables
data = data.dropna(subset=['internetuserate', 'urbanrate'])

In [6]:
data['urbanrate'] = data['urbanrate'] - data['urbanrate'].mean()
#subtracting the mean from explanatory variable
data['urbanrate'].mean() #see? the mean is close to 0!

1.3201136090700809e-14

In [7]:
X = np.asarray(data['urbanrate'])
y = np.asarray(data['internetuserate'])

regr = sm.OLS(y, X)
result = regr.fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.143
Model:                            OLS   Adj. R-squared:                  0.138
Method:                 Least Squares   F-statistic:                     31.50
Date:                Fri, 29 Mar 2019   Prob (F-statistic):           7.02e-08
Time:                        20:02:07   Log-Likelihood:                -978.61
No. Observations:                 190   AIC:                             1959.
Df Residuals:                     189   BIC:                             1962.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.7202      0.128      5.613      0.000       0.467       0.973
==============================================================================
Omnibus:                       10.750   Durbin-Watson:                   0.578
Prob(Omnibus):                  0.005   Jarque-Bera (JB):               10.990
Skew:                           0.574   Prob(JB):                      0.00411
Kurtosis:                       3.262   Cond. No.                         1.00
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""